### PR TITLE
Subcommands and covariance based tree regression

### PR DESCRIPTION
**Pull request by rneher**
This PR introduces a number of new features
 * the previous scripts`homoplasy_scanner`, `ancestral` etc are replaced in favor of a number of subcommands that are called as `treetime ancestral`, `treetime mugration`, etc
 * the root optimization now takes into account the covariance structure of the tree.
 * a number of efforts to make the code base more consistent, some linting, more consistent import patterns etc.

### CODE REVIEW

**Comment by emmahodcroft** [comment]
I thought this might be a good time to make these scripts/subcommands compatible with VCF as much as possible, since TreeTime can handle this, and people keep asking me how to run TreeTime on VCF input -but feel free to disregard or move :)

**Comment by emmahodcroft** [comment]
That should be everything - and you also can pass a DRM file to the homoplasy scanner so it identifies DRM mutations. This checks against the identified mutations so should work for Fasta, too.

**Comment by emmahodcroft** [comment]
From the [changes](https://github.com/neherlab/treetime/pull/56/commits/1411811ccd29b6cae986f71987d3bb6ed5747c15) in `setup.py` I'm getting an error with the `treetime.wrappers` import at the top of `bin/treetime` ('no module named treetime.wrappers'). With `python3 setup.py install` and `pip install .` Seems to be because of the name change?

**Comment by rneher** [comment]
I don't have this import problem. let's check Monday...

**Comment by emmahodcroft** [comment]
Think the problem was possibly too many treetimes... after some clean-up it's now working :)

**Pull request merged**
